---
- name: Sign Certificate
  hosts: dc01
  become: true
  tasks:
    - name: Generate Private Key
      community.crypto.openssl_privatekey:
        path: >-
          {{ np.key }}
        type: RSA
        size: 4096
    - name: Generate CSR
      community.crypto.openssl_csr:
        path: >-
          {{ np.csr }}
        privatekey_path: >-
          {{ np.key }}
        common_name: >-
          {{ np.cn }}
        subject_alt_name: >-
          {{ np.san }}
    - name: Sign Certificate
      community.crypto.x509_certificate:
        path: >-
          {{ np.crt }}
        privatekey_path: >-
          {{ np.key }}
        csr_path: >-
          {{ np.csr }}
        ownca_path: >-
          {{ int_ca.paths.crt }}
        ownca_privatekey_path: >-
          {{ int_ca.paths.key }}
        # ownca_privatekey_passphrase: >-
        #   {{ secret_ca_passphrase }}
        provider: ownca
        state: present
        mode: 0644
- name: Pull certificate
  hosts: np
  tasks:
    - name: Ensure CSR directory
      ansible.builtin.file:
        dest: "/etc/ssl/csr"
        state: directory
        owner: root
        group: network
        mode: "u+rwx,g+rwx,o+r"
      become: true
    - name: Copy cert files
      ansible.builtin.copy:
        remote_src: >-
          {{ item }}
        dest: >-
          {{ item }}
        owner: root
        group: network
        mode: "u+rw,g+rw,o+r"
      delegate_to: dc01
      loop:
        - >-
          {{ cert.key }}
        - >-
          {{ cert.csr }}
        - >-
          {{ cert.crt }}
    - name: Fix key file perms
      ansible.builtin.file:
        dest: >-
          {{ cert.key }}
        state: present
        owner: root
        group: network
        mode: "u+rw,g-rwx,o-rwx"
