---
- name: Create Intermediate CAs
  hosts: root
  become: true
  tasks:
    - name: Create Intermediate CA key
      community.crypto.openssl_privatekey:
        path: "{{ item.key_path }}"
      loop: "{{ int }}"
    - name: Create certificate signing request (CSR) for new certificate
      community.crypto.openssl_csr:
        backup: true
        create_subject_key_identifier: true
        email_address: "{{ item.email }}"
        privatekey_path: "{{ item.key_path }}"
        subject_alt_name: "{{ item.subj_alt }}"
        path: "{{ item.csr_path }}"
      loop: "{{ int }}"
    - name: Sign certificate with our CA
      community.crypto.x509_certificate:
        csr_path: "{{ item.csr_path }}"
        path: "{{ item.path }}"
        provider: ownca
        ownca_path: "{{ ca_path }}"
        ownca_privatekey_path: "{{ ca_key_path }}"
        ownca_privatekey_passphrase: "{{ secret_ca_passphrase }}"
        ###
        # valid for one year
        ownca_not_after: >-
          +36500d
        ###
        # valid since yesterday
        ownca_not_before: "-1d"
      loop: "{{ int }}"
    - name: Slup the int CA
      ansible.builtin.slurp:
        src: "{{ int[0].path }}"
      register: int_ca
    - name: Debug CA
      ansible.builtin.debug:
        msg: "{{ int_ca }}"
