---
- name: Create root CA
  hosts: all
  become: true
  tasks:
    - name: Add directories
      ansible.builtin.file:
        state: directory
        group: root
        owner: root
        dest: "{{ item }}"
        mode: 'u+rw,g+rw,o+r'
      loop: >-
        {{ ssl_dirs }}
    - name: Create private key with password protection
      community.crypto.openssl_privatekey:
        cipher: auto
        path: '/etc/ssl/private/ca.key'
        passphrase: >-
          {{ secret_ca_passphrase }}
      delegate_to: >-
        {{ dn.cn }}
      run_once: true
    - name: Create certificate signing request (CSR) for CA certificate
      community.crypto.openssl_csr:
        basic_constraints:
          - 'CA:TRUE'
        basic_constraints_critical: true
        common_name: >-
          {{ dn.cn }}
        crl_distribution_points:
          - full_name:
              - "URI:https://{{ dn.cn }}/revocations.crl"
            crl_issuer:
              - "URI:https://{{ dn.cn }}/"
            reasons:
              - key_compromise
              - ca_compromise
              - cessation_of_operation
        email_address: "root@{{ dn.cn }}"
        key_usage:
          - keyCertSign
          - cRLSign
          - digitalSignature
        key_usage_critical: true
        locality_name: "{{ dn.locality }}"
        organization_name: "{{ dn.org }}"
        organizational_unit_name: "{{ dn.unit }}"
        path: '/etc/ssl/csr/ca.csr'
        privatekey_passphrase: "{{ secret_ca_passphrase }}"
        privatekey_path: '/etc/ssl/private/ca.key'
        state_or_province_name: "{{ dn.state }}"
        subject_alt_name: >-
          {{ subj_alt }}
      delegate_to: >-
        {{ dn.cn }}
      run_once: true
    - name: Create self-signed CA certificate from CSR
      community.crypto.x509_certificate:
        csr_path: '/etc/ssl/csr/ca.csr'
        path: '/etc/ssl/certs/ca.crt'
        privatekey_passphrase: "{{ secret_ca_passphrase }}"
        privatekey_path: '/etc/ssl/private/ca.key'
        provider: selfsigned
        return_content: true
        selfsigned_digest: sha256
      delegate_to: >-
        {{ dn.cn }}
      register: certificate
      run_once: true
    - name: Distribute Cert
      ansible.builtin.fetch:
        src: '/etc/ssl/certs/ca.crt'
        dest: '/etc/ssl/certs/ca.crt'
        flat: true
