---
- name: Create root CA
  hosts: ca
  remote_user: duchess
  become: true
  tasks:
    - name: Clean
      ansible.builtin.file:
        state: absent
        dest: "{{ item }}"
      loop: "{{ clean }}"
      tags:
        - clean
    - name: Create private key with password protection
      community.crypto.openssl_privatekey:
        cipher: auto
        path: "{{ ca.key_path }}"
        passphrase: "{{ ca.passphrase }}"
      tags:
        - ca
    - name: Create certificate signing request (CSR) for CA certificate
      community.crypto.openssl_csr:
        authority_cert_issuer: "{{ ca.authority }}"
        authority_cert_serial_number: "1001"
        basic_constraints:
          - 'CA:TRUE'
        basic_constraints_critical: true
        common_name: "{{ ca.common_name }}"
        email_address: "root@{{ ca.common_name }}"
        path: "{{ ca.csr_path }}"
        privatekey_passphrase: "{{ ca.passphrase }}"
        privatekey_path: "{{ ca.key_path }}"
        key_usage:
          - keyCertSign
        key_usage_critical: true
        locality_name: "{{ ca.locality }}"
        organization_name: "{{ ca.org }}"
        organizational_unit_name: "{{ ca.unit }}"
        state_or_province_name: "{{ ca.state }}"
      tags:
        - ca
    - name: Create self-signed CA certificate from CSR
      community.crypto.x509_certificate:
        path: "{{ ca.path }}"
        csr_path: "{{ ca.csr_path }}"
        privatekey_path: "{{ ca.key_path }}"
        privatekey_passphrase: "{{ ca.passphrase }}"
        provider: selfsigned
      tags:
        - ca
