---
- name: Setup Certificate Chain and Keys on Hosts
  hosts: all
  become: true
  tasks:
    - name: Check for Root CA Certificate on "{{ dn.cn }}"
      ansible.builtin.stat:
        path: "/etc/ssl/certs/ca.crt"
      delegate_to: "{{ dn.cn }}"
      register: root_ca_cert
      failed_when: not root_ca_cert.stat.exists

    - name: Check for Intermediate CA Certificate on "{{ dn.cn }}"
      ansible.builtin.stat:
        path: "/etc/ssl/certs/int.ca.crt"
      delegate_to: "{{ dn.cn }}"
      register: intermediate_ca_cert
      failed_when: not intermediate_ca_cert.stat.exists

    - name: Check for Root CA Private Key on "{{ dn.cn }}"
      ansible.builtin.stat:
        path: "/etc/ssl/private/ca.key"
      delegate_to: "{{ dn.cn }}"
      register: root_ca_key
      failed_when: not root_ca_key.stat.exists

    - name: Check for Intermediate CA Private Key on "{{ dn.cn }}"
      ansible.builtin.stat:
        path: '/etc/ssl/private/int.ca.key'
      delegate_to: "{{ dn.cn }}"
      register: intermediate_ca_key
      failed_when: not intermediate_ca_key.stat.exists

    - name: Create Certificate Bundle on "{{ dn.cn }}"
      ansible.builtin.shell:
        cmd: "cat /etc/ssl/certs/ca.crt /etc/ssl/certs/int.ca.crt > /etc/ssl/certs/ca.bundle.crt"
      delegate_to: "{{ dn.cn }}"
      when: root_ca_cert.stat.exists and intermediate_ca_cert.stat.exists
      register: bundle_creation
      changed_when: bundle_creation.rc == 0
      notify:
        - Copy Bundle

    - name: Copy Root CA Private Key to Target Host
      ansible.builtin.copy:
        src: "/etc/ssl/private/ca.key"
        dest: "/etc/ssl/private/ca.key"
        flat: true
      delegate_to: "{{ dn.cn }}"
      become: true
      become_user: root
      when: root_ca_key.stat.exists

    - name: Copy Intermediate CA Private Key to Target Host
      ansible.builtin.copy:
        src: "/etc/ssl/private/int.ca.key"
        dest: "/etc/ssl/private/int.ca.key"
        flat: true
      delegate_to: "{{ dn.cn }}"
      when: intermediate_ca_key.stat.exists

    # Additional configuration for services to use these certificates and keys can be added here.
  handlers:
    - name: Copy Bundle
      ansible.builtin.copy:
        src: "/etc/ssl/certs/ca.bundle.crt"
        dest: "/etc/ssl/certs/ca.bundle.crt"
        flat: true
      delegate_to: "{{ dn.cn }}"
