---
- name: Setup Certificate Chain and Keys on Hosts
  hosts: all
  become: true
  tasks:
    - name: Check for Root CA Certificate on ca.socal.rr.com
      ansible.builtin.stat:
        path: "/etc/ssl/certs/ca.crt"
      delegate_to: "ca.socal.rr.com"
      register: root_ca_cert
      failed_when: not root_ca_cert.stat.exists

    - name: Check for Intermediate CA Certificate on ca.socal.rr.com
      ansible.builtin.stat:
        path: "/etc/ssl/certs/int.ca.crt"
      delegate_to: "ca.socal.rr.com"
      register: intermediate_ca_cert
      failed_when: not intermediate_ca_cert.stat.exists

    - name: Check for Root CA Private Key on ca.socal.rr.com
      ansible.builtin.stat:
        path: "/etc/ssl/private/ca.key"
      delegate_to: "ca.socal.rr.com"
      register: root_ca_key
      failed_when: not root_ca_key.stat.exists

    - name: Check for Intermediate CA Private Key on ca.socal.rr.com
      ansible.builtin.stat:
        path: '/etc/ssl/private/int.ca.key'
      delegate_to: "ca.socal.rr.com"
      register: intermediate_ca_key
      failed_when: not intermediate_ca_key.stat.exists

    - name: Create Certificate Bundle on ca.socal.rr.com
      ansible.builtin.shell:
        cmd: "cat /etc/ssl/certs/ca-cert.pem /etc/ssl/certs/intermediate-cert.pem > /etc/ssl/certs/ca-bundle.pem"
      delegate_to: "ca.socal.rr.com"
      when: root_ca_cert.stat.exists and intermediate_ca_cert.stat.exists
      register: bundle_creation
      changed_when: bundle_creation.rc == 0
      notify:
        - Copy Bundle

    - name: Copy Root CA Private Key to Target Host
      ansible.builtin.fetch:
        src: "/etc/ssl/private/ca-key.pem"
        dest: "/etc/ssl/private/ca-key.pem"
        flat: true
      delegate_to: "ca.socal.rr.com"
      when: root_ca_key.stat.exists

    - name: Copy Intermediate CA Private Key to Target Host
      ansible.builtin.fetch:
        src: "/etc/ssl/private/intermediate-key.pem"
        dest: "/etc/ssl/private/intermediate-key.pem"
        flat: true
      delegate_to: "ca.socal.rr.com"
      when: intermediate_ca_key.stat.exists

    # Additional configuration for services to use these certificates and keys can be added here.
  handlers:
    - name: Copy Bundle
      ansible.builtin.fetch:
        src: "/etc/ssl/certs/ca-bundle.pem"
        dest: "/etc/ssl/certs/ca-bundle.pem"
        flat: true
      delegate_to: "ca.socal.rr.com"
