---
- name: Reset existing nodes
  ansible.builtin.shell:
    cmd: kubeadm reset -f
  register: reset_result
- name: Show reset results
  ansible.builtin.debug:
    var: reset_result.stdout
- name: Delete nodes from cluster
  ansible.builtin.shell:
    cmd: "kubectl delete nodes {{ inventory_hostname }}"
  delegate_to: kcp01
