###
# ```{rubric} Ansible Lint Jobs
# ```
# ---
# This action lints Ansible code for quality.
#
# ```{literalinclude} .github/workflows/ansible-lint.yml
# :language: yaml
# :caption: .github/workflows/ansible-lint.yml
# ```
name: ansible-lint
on:
  pull_request:
    branches: ["main", "stable", "release/v*"]
jobs:
  build:
    ###
    # Naming the build is important to use it as a status check
    name: Ansible Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Set up Python
        uses: actions/setup-python@main
        with:
          python-version: 3.11
      - name: Install requirements
        run: |
          pip3 install ansible
          pip3 install ansible-galaxy
          ansible-galaxy install community.crypto.openssl_privatekey
      - name: Make ansible directory
        run: |
          sudo mkdir -pv /etc/ansible
          SUSER=$(whoami)
          sudo chown ${SUSER} /etc/ansible
          touch /etc/ansible/vault
          echo "Pass" > /etc/ansible/vault
      - name: Run ansible-lint
        ###
        # or version tag instead of 'main'
        uses: ansible/ansible-lint@main
